### ISSUE TITLE
Docker環境構築

### ISSUE THREAD

**Issue by m5151128** [m5151128/angular-tutorial#1]

**Comment by m5151128** [comment]
うまく起動しなかった。。。

```
$  ng serve --open --host 0.0.0.0
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /usr/local/lib/node_modules/@angular/cli/models/architect-command.js
- /usr/local/lib/node_modules/@angular/cli/commands/serve-impl.js
- /usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /usr/local/lib/node_modules/@angular/cli/utilities/json-schema.js
- /usr/local/lib/node_modules/@angular/cli/models/command-runner.js
- /usr/local/lib/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-CW83Dv/angular-errors.log" for further details.
```

これは、[ここ](https://stackoverflow.com/questions/50333003/could-not-find-module-angular-devkit-build-angular) のを参考に↓でいけたぽい
```
$ yarn add @angular-devkit/build-angular --dev
```

**Comment by m5151128** [comment]
```
root@51d133e398b9:/projects# ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.5
Node: 15.11.0
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.5 (cli-only)
@angular-devkit/core         11.2.5 (cli-only)
@angular-devkit/schematics   11.2.5 (cli-only)
@schematics/angular          11.2.5 (cli-only)
@schematics/update           0.1102.5 (cli-only)
```

**Comment by m5151128** [comment]
動かん。。。

```
root@51d133e398b9:/projects/angular-app# ng serve --host 0.0.0.0
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
Compiling @angular/core : es2015 as esm2015
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-vkXevy/angular-errors.log" for further details.
root@51d133e398b9:/projects/angular-app# node:internal/errors:415
    ErrorCaptureStackTrace(err);
    ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at /projects/angular-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:51:21
    at new Promise (<anonymous>)
    at Object.sendMessageToMaster (/projects/angular-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:46:16)
    at /projects/angular-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:104:66
    at step (/projects/angular-app/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/projects/angular-app/node_modules/tslib/tslib.js:124:57)
    at rejected (/projects/angular-app/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by m5151128** [comment]
とりあえず、nodeのバージョンかと思い12系に下げてみる。

```
/projects # ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.5
Node: 12.21.0
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.5 (cli-only)
@angular-devkit/core         11.2.5 (cli-only)
@angular-devkit/schematics   11.2.5 (cli-only)
@schematics/angular          11.2.5 (cli-only)
@schematics/update           0.1102.5 (cli-only)
```

`ng serve --host 0.0.0.0` で↓のエラーなし。
`An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'` 
だけど、warningが無限ループする。ダメだこりゃ。。。

```
/projects/angular-app # ng serve --host 0.0.0.0
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
Compiling @angular/core : es2015 as esm2015
Warning: Worker #1 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/core, formatProperty: es2015, processDts: Yes}
  Current phase: compiling
Compiling @angular/core : es2015 as esm2015
Warning: Worker #2 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/core, formatProperty: es2015, processDts: Yes}
  Current phase: compiling
Compiling @angular/core : es2015 as esm2015
Warning: Worker #3 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/core, formatProperty: es2015, processDts: Yes}
  Current phase: compiling
Compiling @angular/core : es2015 as esm2015
```

**Comment by m5151128** [comment]
次は10系
10系だと`@angular-devkit/build-angular` が入るみたいね。(他のバージョンでも入れよって思う気はする)

```
root@672534da5407:/projects/angular-app# ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.5
Node: 10.24.0
OS: linux x64

Angular: 11.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.5
@angular/cli                    11.2.5
@schematics/angular             11.2.5
@schematics/update              0.1102.5
rxjs                            6.6.6
typescript                      4.1.5
```

```
root@672534da5407:/projects/angular-app# ng serve --host=0.0.0.0
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
Compiling @angular/core : es2015 as esm2015
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-oyDsf1/angular-errors.log" for further details.
root@672534da5407:/projects/angular-app# (node:199) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at process.target._send (internal/child_process.js:762:20)
    at process.target.send (internal/child_process.js:634:19)
    at /projects/angular-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:51:21
    at new Promise (<anonymous>)
    at Object.sendMessageToMaster (/projects/angular-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:46:16)
    at /projects/angular-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:104:66
    at step (/projects/angular-app/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/projects/angular-app/node_modules/tslib/tslib.js:124:57)
    at rejected (/projects/angular-app/node_modules/tslib/tslib.js:115:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:199) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:199) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by m5151128** [comment]
もうわからんからローカルでやるかと思ったら。。。

```
$ npm install -g @angular/cli                                                                                                                                                                                                                                    [±master ●▴]

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/nagayama/.nodebrew/node/v11.3.0/bin/ng -> /Users/nagayama/.nodebrew/node/v11.3.0/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@11.2.5 postinstall /Users/nagayama/.nodebrew/node/v11.3.0/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
how to change this setting, see https://angular.io/analytics. No

+ @angular/cli@11.2.5
added 238 packages from 181 contributors in 295.156s
```

```
$ ng --version
Node.js version v11.3.0 detected.
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
```

んー。諸事情でローカルのnodeのバージョン変えたくないんだよね。
これだからnodeは。

**Comment by m5151128** [comment]
dockerでnodeをv12.0にしたけど、ダメじゃん。。。

```
root@1ae4c5d390e2:/projects/angular-app# ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.5
Node: 12.0.0
OS: linux x64

Angular: 11.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.5
@angular/cli                    11.2.5
@schematics/angular             11.2.5
@schematics/update              0.1102.5
rxjs                            6.6.6
typescript                      4.1.5
```

```
root@1ae4c5d390e2:/projects/angular-app# ng serve --host=0.0.0.0
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
Compiling @angular/core : es2015 as esm2015
Warning: Worker #1 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/core, formatProperty: es2015, processDts: Yes}
  Current phase: compiling
Compiling @angular/core : es2015 as esm2015
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-ZJNqdQ/angular-errors.log" for further details.
root@1ae4c5d390e2:/projects/angular-app# Error: Tried to write /projects/angular-app/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /projects/angular-app/node_modules/@angular/core/core.d.ts.
This error may be caused by one of the following:
* two or more entry-points overlap and ngcc has been asked to process some files more than once.
  In this case, you should check other entry-points in this package
  and set up a config to ignore any that you are not using.
* a previous run of ngcc was killed in the middle of processing, in a way that cannot be recovered.
  In this case, you should try cleaning the node_modules directory and any dist directories that contain local libraries. Then try again.
Error: Tried to write /projects/angular-app/node_modules/@angular/core/core.d.ts.map.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /projects/angular-app/node_modules/@angular/core/core.d.ts.map.
This error may be caused by one of the following:
* two or more entry-points overlap and ngcc has been asked to process some files more than once.
  In this case, you should check other entry-points in this package
  and set up a config to ignore any that you are not using.
* a previous run of ngcc was killed in the middle of processing, in a way that cannot be recovered.
  In this case, you should try cleaning the node_modules directory and any dist directories that contain local libraries. Then try again.
```

**Comment by m5151128** [comment]
v10.13にしてみた。

```
root@99624134fff5:/projects# ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.5
Node: 10.13.0
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.5 (cli-only)
@angular-devkit/core         11.2.5 (cli-only)
@angular-devkit/schematics   11.2.5 (cli-only)
@schematics/angular          11.2.5 (cli-only)
@schematics/update           0.1102.5 (cli-only)
```

```
root@99624134fff5:/projects/angular-app# ng serve --host 0.0.0.0
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-tlOdGz/angular-errors.log" for further details.
root@99624134fff5:/projects/angular-app# Compiling @angular/core : es2015 as esm2015
```


~~おおおおおおおおお。~~
~~初めてエラーが出なかった。ちょっと感動。~~
~~でも、http://localhost:4200 で見れないな。~~

> See "/tmp/ng-tlOdGz/angular-errors.log" for further details.

エラー出てたわ orz

```
root@99624134fff5:/projects/angular-app# cat /tmp/ng-uf2XvS/angular-errors.log
[error] Error: NGCC failed.
    at NgccProcessor.process (/projects/angular-app/node_modules/@ngtools/webpack/src/ngcc_processor.js:129:19)
    at compiler.hooks.thisCompilation.tap (/projects/angular-app/node_modules/@ngtools/webpack/src/ivy/plugin.js:104:27)
    at SyncHook.eval [as call] (eval at create (/projects/angular-app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/projects/angular-app/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/projects/angular-app/node_modules/webpack/lib/Compiler.js:630:30)
    at hooks.beforeCompile.callAsync.err (/projects/angular-app/node_modules/webpack/lib/Compiler.js:667:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/projects/angular-app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/projects/angular-app/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/projects/angular-app/node_modules/webpack/lib/Compiler.js:662:28)
    at compiler.hooks.watchRun.callAsync.err (/projects/angular-app/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/projects/angular-app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/projects/angular-app/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/projects/angular-app/node_modules/webpack/lib/Watching.js:41:32)
    at Watching.compiler.readRecords.err (/projects/angular-app/node_modules/webpack/lib/Watching.js:33:9)
    at Compiler.readRecords (/projects/angular-app/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/projects/angular-app/node_modules/webpack/lib/Watching.js:30:17)
```

**Comment by m5151128** [comment]
結局ローカルでやった。

```
 $ ng --version                                                                                                                                                                                                                                                  [±master ●●▴]

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.5
Node: 14.16.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.5 (cli-only)
@angular-devkit/core         11.2.5 (cli-only)
@angular-devkit/schematics   11.2.5 (cli-only)
@schematics/angular          11.2.5 (cli-only)
@schematics/update           0.1102.5 (cli-only)
```

やっと成功パターンっぽいのみれた。
~~でも、 http://localhost:4200/ にアクセスしても何も表示されん。。。~~
doker起動しっぱなしでポート番号4200が被ってたからだった。

```
 $ ng serve --open                                                                                                                                                                                                                                               [±master ●●▴]
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.43 MB
polyfills.js        | polyfills     | 128.76 kB
main.js             | main          |  53.36 kB
runtime.js          | runtime       |   6.15 kB
styles.css          | styles        | 119 bytes

                    | Initial Total |   2.62 MB

Build at: 2021-03-22T06:34:24.443Z - Hash: 802037d69eee53e51c2e - Time: 11322ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names  |      Size
styles.css          | styles | 119 bytes

4 unchanged chunks

Build at: 2021-03-22T06:34:25.010Z - Hash: 1ecd6e6fe1a0eb520398 - Time: 255ms

✔ Compiled successfully.
```

**Comment by m5151128** [comment]
dockerだとうまくいかないのは、
`ng new` したときに出てる以下が問題な気がしなくもない。。。？

```
⠙ Installing packages (npm)...npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Killed
✖ Package install failed, see above.
The Schematic workflow failed. See above.
```

**Comment by m5151128** [comment]
答え：
dockerのswapが足りなかっただけだったああああああ
